- name: Rollback node_exporter installation
  hosts: node_exporter
  become: true

  tasks:
    - name: Stop node_exporter service
      systemd:
        name: node_exporter
        state: stopped
        enabled: no
        masked: yes

    - name: Remove node_exporter service file
      file:
        path: /etc/systemd/system/node_exporter.service
        state: absent

    - name: Remove node_exporter binary
      file:
        path: /usr/local/bin/node_exporter
        state: absent

    - name: Remove SELinux fcontext rule for node_exporter
      command: semanage fcontext -d /usr/local/bin/node_exporter
      ignore_errors: yes

    - name: Reload systemd daemon
      command: systemctl daemon-reload
